/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Billy Jackman (https://sketchfab.com/billyjackman3d)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ring-blade-fantasy-game-weapon-e65dc6a7abda4626b367d5a5122c3849
title: Ring Blade - Fantasy Game Weapon
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/circle/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.34}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.RingBlade_MAT} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.RingBlade_MAT} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.RingBlade_MAT} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
